/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tetris_TetrisInput */

#ifndef _Included_tetris_TetrisInput
#define _Included_tetris_TetrisInput
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tetris_TetrisInput
 * Method:    getKeyPress
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tetris_TetrisInput_getKeyPress
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
